# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-10 07:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utilisateurs', '0004_auto_20170509_1743'),
    ]

    operations = [
        migrations.CreateModel(
            name='A_Ecrit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Auteur',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.TextField()),
                ('prenom', models.TextField()),
                ('nom_auteur', models.TextField()),
                ('mail', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Distributeur',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.TextField()),
                ('mail', models.TextField()),
                ('tel', models.TextField()),
                ('fax', models.TextField()),
                ('adresse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilisateurs.Adresse')),
            ],
        ),
        migrations.CreateModel(
            name='Editeur',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.TextField()),
                ('mail', models.TextField()),
                ('adresse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilisateurs.Adresse')),
                ('distributeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livres.Distributeur')),
            ],
        ),
        migrations.CreateModel(
            name='Est_Genre',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Est_Theme',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('genre', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Langue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('langue', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Livre',
            fields=[
                ('isbn', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.TextField()),
                ('prix', models.IntegerField()),
                ('annee', models.IntegerField()),
                ('quantite', models.IntegerField()),
                ('editeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livres.Editeur')),
                ('langue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livres.Langue')),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('theme', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='est_theme',
            name='id_livre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livres.Livre'),
        ),
        migrations.AddField(
            model_name='est_theme',
            name='id_theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livres.Theme'),
        ),
        migrations.AddField(
            model_name='est_genre',
            name='id_genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livres.Genre'),
        ),
        migrations.AddField(
            model_name='est_genre',
            name='id_livre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livres.Livre'),
        ),
        migrations.AddField(
            model_name='a_ecrit',
            name='id_auteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livres.Auteur'),
        ),
        migrations.AddField(
            model_name='a_ecrit',
            name='id_livre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livres.Livre'),
        ),
    ]
