# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-15 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livres', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='langue',
            name='sigle',
            field=models.CharField(default='fr', max_length=8),
        ),
        migrations.AlterField(
            model_name='langue',
            name='langue',
            field=models.CharField(max_length=40),
        ),
    ]
