# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-15 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livres', '0002_auto_20170515_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='langue',
            name='sigle',
            field=models.CharField(default='', max_length=8),
        ),
    ]
