# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-15 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livres', '0004_auto_20170515_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auteur',
            name='nom_auteur',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='distributeur',
            name='nom',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='editeur',
            name='nom',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='genre',
            name='genre',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='theme',
            name='theme',
            field=models.TextField(unique=True),
        ),
    ]
