# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-11 13:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('livres', '0001_initial'),
        ('utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_emmission', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.IntegerField()),
                ('quantite', models.IntegerField()),
                ('expediee', models.BooleanField(default=False)),
                ('nom', models.CharField(max_length=30)),
                ('prenom', models.CharField(max_length=30)),
                ('adresse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilisateurs.Adresse')),
                ('commanditaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilisateurs.Utilisateur')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livres.Livre')),
            ],
        ),
    ]
