# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-11 13:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Adresse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.IntegerField()),
                ('nom', models.CharField(max_length=100)),
                ('commune', models.CharField(max_length=101)),
                ('cp', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Type_Voie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='utilisateurs.Adresse')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='adresse',
            name='type_voie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilisateurs.Type_Voie'),
        ),
    ]
