# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 14:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mdp', models.CharField(max_length=64)),
                ('pseudo', models.TextField()),
                ('nom', models.TextField()),
                ('prenom', models.TextField()),
                ('mail', models.TextField()),
                ('tel', models.TextField()),
                ('adresse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
