# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 14:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adresse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.IntegerField()),
                ('nom', models.CharField(max_length=100)),
                ('commune', models.CharField(max_length=101)),
                ('cp', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Type_Voie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='adresse',
            name='type_voie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilisateurs.Type_Voie'),
        ),
    ]
