# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 15:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0002_auto_20170509_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='true_ad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='utilisateurs.Adresse'),
        ),
    ]
